# keras

In [10]:
import tensorflow as tf
import numpy as np

## dropout

In [39]:
inputs_ = np.random.random((10,2))
inputs_

array([[0.4414361 , 0.35401628],
       [0.07302825, 0.43258472],
       [0.04011253, 0.52821924],
       [0.949973  , 0.41101471],
       [0.08350503, 0.58673675],
       [0.44707561, 0.30970771],
       [0.6083927 , 0.35133495],
       [0.96664631, 0.61926354],
       [0.04375122, 0.15177627],
       [0.79663477, 0.84121058]])

In [52]:
dropout_layer = tf.keras.layers.Dropout(.5, input_shape=(2,))

In [53]:
dropout_layer(inputs_, training=True)

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[0.8828722 , 0.        ],
       [0.        , 0.86516947],
       [0.08022505, 1.0564384 ],
       [1.899946  , 0.        ],
       [0.        , 1.1734735 ],
       [0.8941512 , 0.        ],
       [1.2167854 , 0.7026699 ],
       [0.        , 1.238527  ],
       [0.        , 0.        ],
       [1.5932696 , 0.        ]], dtype=float32)>

## batch normalization

In [55]:
bn_layer = tf.keras.layers.BatchNormalization(input_shape=(2,))

In [60]:
outputs_ = bn_layer(inputs_, training=True)
outputs_

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[-0.01011086, -0.5628536 ],
       [-1.0392594 , -0.13995576],
       [-1.1312096 ,  0.37480068],
       [ 1.4104885 , -0.25605726],
       [-1.0099925 ,  0.68977356],
       [ 0.00564313, -0.8013463 ],
       [ 0.45628297, -0.5772859 ],
       [ 1.4570655 ,  0.8648505 ],
       [-1.1210449 , -1.6514186 ],
       [ 0.9821378 ,  2.0594897 ]], dtype=float32)>

In [63]:
np.mean(outputs_.numpy(), axis=0)

array([ 5.9604645e-08, -2.8610231e-07], dtype=float32)

In [64]:
np.std(outputs_.numpy(), axis=0)

array([0.9960905 , 0.98540765], dtype=float32)

In [65]:
## Lambda

In [66]:
lambda_layers = tf.keras.layers.Lambda(lambda x: tf.subtract(x, 10))

In [67]:
lambda_layers(inputs_)

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[-9.558564 , -9.645984 ],
       [-9.926971 , -9.567415 ],
       [-9.9598875, -9.471781 ],
       [-9.050027 , -9.588985 ],
       [-9.916495 , -9.413263 ],
       [-9.552924 , -9.690292 ],
       [-9.391607 , -9.648665 ],
       [-9.033354 , -9.380736 ],
       [-9.956249 , -9.848224 ],
       [-9.203365 , -9.15879  ]], dtype=float32)>

## ReLU

In [71]:
relu_layers = tf.keras.layers.ReLU()

In [74]:
relu_layers(100)

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [75]:
relu_layers(-100)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [76]:
## LeakyReLU

In [77]:
leaky_relu_layer = tf.keras.layers.LeakyReLU()

In [78]:
leaky_relu_layer(100)

<tf.Tensor: shape=(), dtype=float32, numpy=100.0>

In [79]:
leaky_relu_layer(-1)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.3>

In [80]:
leaky_relu_layer(-100)

<tf.Tensor: shape=(), dtype=float32, numpy=-30.000002>

## ELU

In [86]:
elu_layers = tf.keras.layers.ELU()

In [89]:
elu_layers(100.)

<tf.Tensor: shape=(), dtype=float32, numpy=100.0>

In [90]:
elu_layers(-1.)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.6321205>

In [91]:
elu_layers(-100.)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0>

## Clipped ReLU

In [93]:
clipped_relu_layers = tf.keras.layers.ReLU(max_value=2)

In [94]:
clipped_relu_layers(100)

<tf.Tensor: shape=(), dtype=int32, numpy=2>